### ISSUE TITLE
Add a possibility to import components independently

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/design#14]
# Introduction

There is no easy way to resolve independent components from `dist` directory without having `/dist/` in path, like in the following example:

```js
import Icon from '@oacore/design/dist/components/icon'
```

It would be nice to avoid this to have flexibility with build directory along with better user experience.

# Objective

The possibility to import independent components might look like in the following example:

```js
import Icon from '@oacore/design/components/icon'
```

There are a few ways to achieve that.

# Possible solutions

#### Pros:
- works well for production
#### Cons:
- does not work for development
  - unless we (npm) link `dist` as package root

#### Pros:
- works for both cases
#### Cons:
- creates mess in the project root
- does not work for Windows
  - unless we use an NPM package for cross-OS aliasing

#### Pros:
- creates a convention: child modules always in the `lib`
- looks kind of native
#### Cons:
- paths are not so pretty

**Comment by viktor-yakubiv** [comment]
Partially solved in #37

**Comment by Joozty** [comment]
I think we can close it, can't we? Do you want to go even further? If so we could create a simple plugin for next which would wrap whole webpack config as I once told you. This plugin would give aliases similar as [`next` does it](https://github.com/zeit/next.js/blob/canary/packages/next/build/webpack-config.ts#L335-L338).

In next.config.js
```
import { withDesign } from '@oacore/design'
...
export default withDesign(withImages(nextConfig))
``

**Comment by viktor-yakubiv** [comment]
This is interesting. I would rather go for more native way, i.e. publish correct directory structure. However, it's a good point. Let's close the issue in favour of #37!
