### ISSUE TITLE
Develop a Link component

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/design#205]
Add a wrapper around the `<a>` element. The interface should be similar to [Vercel's Link](https://vercel.com/design/link):

```jsx
<Link href="https://core.ac.uk" external>CORE</Link>
```

I propose to support only `external` prop at the moment. The icon for the `external` links should probably be added always but let's not do it later because there is a caveat: what if the link is wrapped around a _Card_ or any other element.

We can consider other props later. However, it will probably be `noIcon`. The colour should be always overridden by CSS, we are not going to support it ever.

**Comment by viktor-yakubiv** [comment]
I think that we can support the `variant` for the Link. A variant can add an icon or slightly change the look. However, it makes it quite complex when the Button becomes dependent on this component.

**Comment by Joozty** [comment]
@viktor-yakubiv do you want to make button dependent on Link? I would say these elements should be separated. And even if users use `<Button href="/" tag="a" />` the button component should behave as is now. Do you have a different point of view? 🙂

**Comment by viktor-yakubiv** [comment]
I think that the `tag` prop should not be allowed for both Button and Link:
1. the Link always is `<a>`
2. the Button detects the tag based on the `href` prop: `href != null ? Link : 'button'`.

I do not like such dependency but I was thinking that this way is more useful.

From the second point, we see that the button cannot be an `<input>`. It's more intentional, I do not mind removing such support since we assume having children always. Also, I was thinking about `<Button tag="span" />`: this is semantically wrong and should not be allowed too.
