### ISSUE TITLE
ProgressSprinner animation is too heavy

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/design#222]
It seems the `ProgressSpinner` component is too heavy. When the documentation is open in any browser, my laptop shows that the browser uses significant energy and the cooler starts working hard. I got the animation from the internet and it does not seem to be so heavy to me. I hope it does not affect the performance for short amounts of time.

We should investigate how to optimise this is possible.

_Originally posted in [#220 (comment)](https://github.com/oacore/design/pull/220#issuecomment-660990199)_

**Comment by Joozty** [comment]
After some dig in and using Chrome's performance monitor, I can confirm it used quite a lot of CPU. I checked other libraries and different approaches for spinners and I could see always spike in CPU usage.

 I am not sure if there is a better option for us. We can do some optimisation though - run animation only when the spinner is visible. (especially it's not needed when label covers whole text field.)

This slightly reduces CPU overhead https://github.com/oacore/design/pull/223 but obviously doesn't solve it.

**Comment by viktor-yakubiv** [comment]
Thank you for exploring this. I am happy to know Chrome DevTools have performance monitor. If I knew I would test it myself, sorry I did not explore it and just left the issue.

> That being said we shouldn't overuse spinner on our sites.

We should properly document it in the MD or even better JS file next to the component.

**Comment by Joozty** [comment]
I didn't know either. It has even more tools for profiling/debugging these kinds of issues. 

Another possibility is to use different (ugliest) animation which drains fewer resources or somehow incorporate requestAnimationFrame (not sure about that).  I can imagine that some older computers or browsers with disabled GPU acceleration can be affected more. 🤔
