### ISSUE TITLE
Rename Select component

### ISSUE THREAD

**Issue by Joozty** [oacore/design#271]
The current select component is not a really select it's more input with the suggestions, therefore, it would be better to rename to something more appropriate.

My ideas is to rename it to **Search** and **Search.Suggestion**. WDYT?

**Comment by viktor-yakubiv** [comment]
I consider the Select component being something in between these two: Search form and actual custom Select. You can pick either direction you want. Thanks to versioning we can change it later with low effort.

**Comment by Joozty** [comment]
Let's leave it as is then
