### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by viktor-yakubiv** [oacore/design#290]
#289 made me think what is the more elegant way to create tooltips and after some boiling my mind I came to the conclusion that hooks are the most powerful for this case.

```jsx
const DataProviderRegistration = (props) => {
  const tooltip = useTooltip(() => (
    <>Rich <b>text</b> formatted tooltip</>
  ), deps)

  return (
    <Card>
      Card content
      <Button {...tooltip}></Button>
    </Card>
  )
}
```

where the `tooltip` object is something like

```js
{
  'aria-describedby': tooltipId,
  onClick: () => {
    callTippy()
  }
}
```

The tooltip itself is rendered somewhere in portal.

**Comment by viktor-yakubiv** [comment]
@Joozty I saw your proposal somewhere but I forgot where the issue was and could not find it here. Sorry, if I duplicated this. If there is any other related issue, please, link it to this one.

**Comment by Joozty** [comment]
The proposal is here https://github.com/oacore/dashboard/issues/71. 

Even though what you are proposing looks the best I have no idea how to make it work.  We would need to manipulate DOM inside that hook and that doesn't look much reactish. I don't think it's worth of implementation. The tooltips shouldn't be overused so whether you use `<Tooltip />` or `useTooltip` won't make any difference in a project unless you argue.  I would rather stick with the interface we already have (including the change described [here](https://github.com/oacore/design/pull/289#discussion_r473923073))

**Comment by viktor-yakubiv** [comment]
> We would need to manipulate DOM inside that hook and that doesn't look much reactish.

I don't think so. The `useTooltip` hook accepts react component should be rendered and returns all the properties should be appended to a trigger.

When the hook is called, it adds a component to some set which is rendered somewhere.

Let's imagine our app in the following way:

```jsx
const App = () => (
  <>
    <Component />
    <Tooltips />
  </>
)
```

and the Component is what I described above:

```jsx
const Component = () => (
  <Card>
    Card content
    <Button {...useTooltip('Hah!')}></Button>
  </Card>
)
```

The proposed `Tooltips` component is a root for tooltips, it can collect all tooltips via `useEffect` and `useContext`.
It would be good to find a better name for the component, maybe `TooltipRoot` or something.

I don't have a strong argument here. I think, what is reactish is not necessarily right. Attributes (props) should only accept bare strings (as in the HTML), passing HTML-like code into HTML attribute increases abstraction level and hams readability, in my opinion.

The advantage of my proposal is that tooltips can be mixed with the component or separated somewhere as functions/components. We potentially can pass some parameter to components but I can't find any use for this at the moment.

In the same time, the equivalent code for the above would be:

```jsx
<Tooltip content="Hah!">
  <Button>Hover on me</Button>
</Tooltip>
```

It's very simple and maybe it's easy to read and understand. In the same time, it requires either wrapper with event listener or cloning the element:
- the wrapper increases DOM complexity
- cloning is tricky when you want to override already defined event (let's say `onFocus`):
  1. if it's defined, we show the tooltip first or call the user event listener first?
  2. if the user prevents default, should the tooltip be dismissed?
  3. should the tooltip be preventable at all?

In the hook case, we allow the user to destructure `{ onHover, onFocus }` and decide but it's tricky too: if the hook result is passed blindly, it can redefine the custom actions what may no be noticed.

I am happy with both, neither is ideal 🙂
