### ISSUE TITLE
Introduce extra-small variant of TextFields

### ISSUE THREAD

**Issue by Joozty** [oacore/design#55]
I think we should have more size options for TextFields at least one more - extra small. I don't like the name maybe you have a better name for it. This size should match size of checkboxes in the data table perhaps.

@viktor-yakubiv What do you think? Or it's better to override this in dashboard?

**Comment by viktor-yakubiv** [comment]
How is this resolved?

**Comment by Joozty** [comment]
There is no need for it now. Maybe in the future....
